[package]
name = "evm-wallet-api"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2"
axum = "0.6"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
bip39 = "2.2.0"
